const Alljokes = [
        "Why don't scientists trust atoms? Because they make up everything!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What did one wall say to the other wall? I'll meet you at the corner!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why did the bicycle fall over? Because it was two-tired!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What do you call a fish wearing a crown? King Neptune!",
        "How do you make a tissue dance? You put a little boogie in it!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "Why don't vampires go to barbecues? They don't like steak!",
        "What did one hat say to the other hat? You stay here, I'll go on ahead!",
        "Why don't melons get married? Because they can't elope!",
        "Why did the math book look sad? Because it had too many problems!",
        "What did one elevator say to the other elevator? I think I'm coming down with something!",
        "How does a penguin build its house? Igloos it together!",
        "What did the left eye say to the right eye? Between you and me, something smells!",
        "Why don't scientists trust atoms? Because they make up everything!",
        "How do you organize a space party? You planet!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What did the ocean say to the shore? Nothing, it just waved!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What's the best thing about Switzerland? I don't know, but their flag is a big plus!",
        "Why couldn't the bicycle stand up by itself? It was two-tired!",
        "What did one snowman say to the other snowman? Do you smell carrots?",
        "Why was the math book sad? Because it had too many problems!",
        "What do you call a bear with no teeth? A gummy bear!",
        "Why did the stadium get hot after the game? All of the fans left!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "How do you make a tissue dance? You put a little boogie in it!",
        "There’s a fine line between a numerator and a denominator.",
        "What do dentists call their x-rays? Tooth pics!",
        "Did you hear about the first restaurant to open on the moon? It had great food, but no atmosphere.",
        "What did one ocean say to the other ocean? Nothing, it just waved.",
        "Do you want to hear a construction joke? Sorry, I’m still working on it.",
        "Did you hear about the fire at the circus? It was in tents!",
        "Why do ducks have feathers? To cover their butt quacks!",
        "What’s the difference between a hippo and a zippo? One is really heavy and the other’s a little lighter.",
    "What does a nosey pepper do? It gets jalapeño business.",
    "Why should you never trust stairs? They’re always up to something.",
  "When does a joke become a ‘dad’ joke? When it becomes apparent.",
  "Why did the bullet end up losing his job? He got fired.",
  "What kind of shorts do clouds wear? Thunderpants",
  "I entered ten puns in a contest to see which would win. No pun in ten did.",
  "How do you measure a snake? In inches—they don’t have feet.",
  "Where does a waitress with only one leg work? IHOP.",
  "What does a house wear? Address!",
  "Why are toilets always so good at poker? They always get a flush",
  "Why is Peter Pan always flying? Because he Neverlands. (I love this joke because it never grows old.)",
  "You heard the rumor going around about butter? Never mind, I shouldn’t spread it.",
  "Two windmills are standing on a wind farm. One asks, ‘What’s your favorite kind of music?’ The other replies, ‘I’m a big metal fan.’",
  "The first rule of the Alzheimer’s club is… Wait, where are we again?",
  "I took the shell off of my racing snail, thinking it would make him faster. But if anything, it made him more sluggish.",
  "What do you get from a pampered cow? Spoiled milk.",
  "How does NASA organize a party? They planet.",
  "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
  "You know, it was so cold in D.C. the other day, I saw a politician with his hands in his own pockets.",
  "How many tickles does it take to get an octopus to laugh? Ten tickles",
  "Why doesn’t Dracula have any friends? Well, honestly, he’s a real pain in the neck.",
  "My teachers told me I’d never amount to much since I procrastinate so much. I told them, “Just you wait!”",
  "Why were they called the “dark ages?” Because there were a lot of knights.",
  "What gets wetter the more it dries? A towel.",
  "Why aren’t koalas considered bears? They don’t have the right koala-fications.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "A Roman legionnaire walks into a bar, holds up two fingers and says, “Five beers, please.”",
  "I tried to catch fog yesterday. Mist.",
  "Working in a mirror factory is something I can totally see myself doing.",
  "Someone stole my mood ring yesterday. I still don’t know how I feel about that.",
  "A horse walks into a bar. The bartender says, “Why the long face?” The horse replies, “Sure.”",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call a cow with a twitch? Beef jerky.",
  "I started a new job as a tailor last week. It’s been sew-sew.",
  "What concert only costs 45 cents? 50 Cent featuring Nickleback.",
  "What kind of shoes does a spy wear? Sneakers.",
  "I’ve been trying to make a sarcastic club, but it’s been really hard to tell if people are interested in joining or not.",
  "And the Lord said unto John, “Come forth and you will receive eternal life.” But John came fifth and won a toaster.",
  "What do you call a fake noodle? An impasta.",
  "My wife accused me the other day of being too immature. I told her there were no girls allowed in my fort.",
  "Someone stole my Microsoft Office and they’re gonna pay. You have my Word.",
  "What do you call a dog with no legs? It doesn’t matter, it’s not going to come anyway.",
  "You know what they say about cliffhangers…",
  "Why does a chicken coop only have two doors? Because if it had four doors, it would be a chicken sedan.",
  "A sandwich walks into a bar. The bartender says, “Sorry, we don’t serve food here.”",
  "I got a new job last week as the new top dog at Old MacDonald’s farm. I’m the new C-I-E-I-O.",
  "Someone stole my mood ring yesterday. I still don’t know how I feel about that.",
  "A Roman legionnaire walks into a bar, holds up two fingers and says, “Five beers, please.”",
  "I tried to catch fog yesterday. Mist.",
  "Working in a mirror factory is something I can totally see myself doing.",
  "Someone stole my mood ring yesterday. I still don’t know how I feel about that.",
  "A horse walks into a bar. The bartender says, “Why the long face?” The horse replies, “Sure.”",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call a cow with a twitch? Beef jerky.",
  "I started a new job as a tailor last week. It’s been sew-sew.",
  "What concert only costs 45 cents? 50 Cent featuring Nickleback.",
  "What kind of shoes does a spy wear? Sneakers.",
  "I’ve been trying to make a sarcastic club, but it’s been really hard to tell if people are interested in joining or not.",
  "And the Lord said unto John, “Come forth and you will receive eternal life.” But John came fifth and won a toaster.",
  "What do you call a fake noodle? An impasta.",
  "My wife accused me the other day of being too immature. I told her there were no girls allowed in my fort.",
  "Someone stole my Microsoft Office and they’re gonna pay. You have my Word.",
  "What do you call a dog with no legs? It doesn’t matter, it’s not going to come anyway.",
  "You know what they say about cliffhangers…",
  "Why does a chicken coop only have two doors? Because if it had four doors, it would be a chicken sedan.",
  "A sandwich walks into a bar. The bartender says, “Sorry, we don’t serve food here.”",
  "I got a new job last week as the new top dog at Old MacDonald’s farm. I’m the new C-I-E-I-O.",
  "Someone stole my mood ring yesterday. I still don’t know how I feel about that.",
  "A Roman legionnaire walks into a bar, holds up two fingers and says, “Five beers, please.”",
  "I tried to catch fog yesterday. Mist.",
  "Working in a mirror factory is something I can totally see myself doing.",
  "Someone stole my mood ring yesterday. I still don’t know how I feel about that.",
  "A horse walks into a bar. The bartender says, “Why the long face?” The horse replies, “Sure.”",
  "How do you make a tissue dance? Put a little boogie in it.",
  "What do you call a cow with a twitch? Beef jerky.",
  "I started a new job as a tailor last week. It’s been sew-sew.",
  "What concert only costs 45 cents? 50 Cent featuring Nickleback.",
  "What kind of shoes does a spy wear? Sneakers.",
  "I’ve been trying to make a sarcastic club, but it’s been really hard to tell if people are interested in joining or not.",
  "And the Lord said unto John, “Come forth and you will receive eternal life.” But John came fifth and won a toaster.",
  "What do you call a fake noodle? An impasta.",
  "My wife accused me the other day of being too immature. I told her there were no girls allowed in my fort.",
  "Someone stole my Microsoft Office and they’re gonna pay. You have my Word.",
  "What do you call a dog with no legs? It doesn’t matter, it’s not going to come anyway.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do we want? Low-flying airplane noises! When do we want them? Nnnnneeeeeeeeeeoooooooooow!",
  "I tried to win a suntanning competition. But all I got was bronze.",
  "How much space will be freed in the EU after Brexit? Approximately 1 GB.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call malware on a Kindle? A bookworm.",
  "Did you hear about the painter who was hospitalized? The doctors say it was due to too many strokes.",
  "Why are crabs so bad at sharing? Because they’re all shellfish.",
  "You: What cartoon mouse walks on two feet? Them: Mickey Mouse You: What duck walks on two feet? Them: Donald Duck You: No, all ducks do!",
  "Want to hear a joke about a roof? The first one’s on the house.",
  "What’s a pirate’s favorite letter? You probably think it’s “R” but it be the “C”.",
  "How much teddy bears never want to eat anything? Because they’re always stuffed.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Where should you go in the room if you’re feeling cold? The corner—they’re usually 90 degrees.",
  "I can never take my dog to the park because the ducks keep trying to bite him. I guess that’s what I get for buying a pure bread dog.",
  "What’s the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
  "What did the Buddhist ask the hot dog vendor? “Make me one with everything.”",
  "You know why you never see elephants hiding up in trees? Because they’re really good at it.",
  "A horse walks into a bar. The bartender says, “Why the long face?”",
  "How did the hipster burn his mouth? He ate his pizza before it was cool.",
  "What do you get when you cross a dyslexic, an insomniac, and an agnostic? Someone who lays awake at night wondering if there’s a dog.",
  "As a scarecrow, people say I’m outstanding in my field. But hay, it’s in my jeans.",
  "Why don’t blind people skydive? Because it scares their dogs.",
  "What’s the difference between an oral thermometer and a rectal thermometer? The taste, mostly.",
  "I stayed up all night and tried to figure out where the sun was. Then it dawned on me.",
  "I told my friend ten jokes to make him laugh. Sadly, no pun in ten did.",
  "I couldn’t believe the highway department called my dad a thief. But when I got home, the signs were all there.",
  "Why did the cowboy get a wiener dog? He wanted to get a long little doggie.",
  "Can a kangaroo jump higher than the Empire State Building? Of course! The Empire State Building can’t jump.",
  "What did the duck say when it bought some lipstick? “Put it on my bill.”",
  "George Clooney, Leonardo DiCaprio, and Matthew McConaughey get together to make a movie. Clooney says, “I’ll direct.” DiCaprio says, “I’ll act.” McConaughey says, “I’ll write, I’ll write, I’ll write.”",
  "A horse walks into a bar. The bartender says, “Hey!” The horse replies, “Sure.”",
  "I googled “Rorshach test.” But for some reason, all that came up were pictures of my parents fighting.",
  "What do kids play when their mom is using the phone? Bored games.",
    "What do you call an ant who fights crime? A vigilANTe!",
    "Why are snails slow? Because they’re carrying a house on their back.",
    "What’s the smartest insect? A spelling bee!",
    "What does a storm cloud wear under his raincoat? Thunderwear.",
    "What is fast, loud and crunchy? A rocket chip.",
    "How does the ocean say hi? It waves!",
    "What do you call a couple of chimpanzees sharing an Amazon account? PRIME-mates.",
    "Why did the teddy bear say no to dessert? Because she was stuffed.",
    "Why did the soccer player take so long to eat dinner? Because he thought he couldn’t use his hands.",
    "Name the kind of tree you can hold in your hand? A palm tree!",
    "What do birds give out on Halloween? Tweets.",
    "What has ears but cannot hear? A cornfield.",
    "What’s a cat’s favorite dessert? A bowl full of mice-cream.",
    "Where did the music teacher leave her keys? In the piano!",
    "What did the policeman say to his hungry stomach? “Freeze. You’re under a vest.”",
    "What did the left eye say to the right eye? Between us, something smells!",
    "What do you call a guy who’s really loud? Mike.",
    "Why do birds fly south in the winter? It’s faster than walking!",
    "What did the lava say to his girlfriend? “I lava you!”",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "What did Yoda say when he saw himself in 4k? HDMI.",
    "Which superhero hits home runs? Batman!",
    "What’s Thanos’ favorite app on his phone? Snapchat.",
    "Sandy’s mum has four kids; North, West, East. What is the name of the fourth child? Sandy, obviously!",
    "What is a room with no walls? A mushroom.",
    "Why did the blue jay get in trouble at school? For tweeting on a test!",
    "What social events do spiders love to attend? Webbings.",
    "What did one pickle say to the other? Dill with it.",
    "What is brown, hairy and wears sunglasses? A coconut on vacation.",
    "Why is a football stadium always cold? It has lots of fans!",
    "What did one math book say to the other? “I’ve got so many problems.”",
    "What did the Dalmatian say after lunch? That hit the spot!",
    "What do you call two bananas on the floor? Slippers.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "Why do ducks have feathers on their tails? To cover their butt quacks.",
    "How does a vampire start a letter? “Tomb it may concern…”",
    "A plane crashed in the jungle and every single person died. Who survived? Married couples.",
    "What kind of math do birds love? Owl-gebra!",
    "Why can’t you ever tell a joke around glass? It could crack up.",
    "What do you call a Star Wars droid that takes the long way around? R2 detour.",
    "How do you stop an astronaut’s baby from crying? You rocket.",
    "Why did the scarecrow win a Nobel prize? Because she was outstanding in her field.",
    "How do you know when a bike is thinking? You can see their wheels turning.",
    "Why was 6 afraid of 7? Because 7,8,9.",
    "What goes up and down but doesn’t move? The staircase.",
    "What kind of shoes do frogs love? Open-toad!",
    "How did the baby tell his mom he had a wet diaper? He sent her a pee-mail.",
    "What is a witch’s favorite subject in school? Spelling.",
    "What’s brown and sticky? A stick.",
    "Why do ducks always pay with cash? Because they always have bills!",
    "How did Benjamin Franklin feel holding his kite when he discovered electricity? Shocked!",
    "When does a joke become a “dad” joke? When the punchline is a parent.",
    "How much did the man sell his dead batteries for? Nothing, they were free of charge!",
    "Where do most horses live? In neighhh-borhoods!",
    "Why did the Daddy Rabbit go to the barber? He had a lot of little hares.",
    "How do you make a lemon drop? Let it fall from the tree.",
    "Why can’t you ever trust atoms? Because they make up everything.",
    "Which planet loves to sing? Nep-tune!",
    "What’s a private investigator’s favorite shoe? Sneak-ers.",
    "What did the limestone say to the geologist? Don’t take me for granite!",
    "If an electric train is traveling south at 10 miles per hour and the wind is blowing North at 10 miles per hour, which way does the smoke blow? Fooled you! Electric trains don’t blow smoke.",
    "Why are basketball courts always wet? Because the players dribble.",
    "How do billboards talk? Sign language.",
    "What do you call a duck that gets good grades? A wise quacker.",
    "What do you call a fish without an eye? A fsh.",
    "What kind of keys are sweet? Cookies!",
    "What board game does the sky love to play? Twister.",
    "Why does a seagull fly over the sea? Because if it flew over the bay, it would be a baygull.",
    "What do you call a tired bull? A bulldozer.",
    "What do you call cheese that belongs to someone else? Nacho cheese!",
    "Why are pizza jokes the worst? They’re too cheesy.",
    "What kind of water cannot freeze? Hot water.",
    "Why was the belt arrested? Because it was holding up some pants.",
    "Why did the peanut get into a rocket? He wanted to be an astro-nut!",
    "Did you hear the joke about the roof? Never mind, it would go over your head.",
    "Why did the cookie go to the hospital? Because it was feeling a little crummy.",
    "What did the ghost call his Mum and Dad? His transparents.",
    "What fruit do twins love? Pears!",
    "What time is it when people are throwing pieces of bread at your head? Time to duck.",
    "Why was the baby strawberry crying? Because their parents were in a jam.",
    "Why don’t you ever see giraffes in middle school? Because they’re all in high school.",
    "How do bees brush their hair? With honeycombs!",
    "What do you do if someone rolls their eyes at you? Roll them right back.",
    "What did the Baby Corn say to the Mama Corn? “Where is Pop Corn?”",
    "What gets wetter the more it dries? A towel.",
    "Why won’t peanut butter tell you a secret? He’s afraid you’ll spread it!",
    "What’s the difference between a car and a fish? You can tune a car but you can’t tuna fish.",
    "What is worse than raining cats and dogs? Hailing taxis.",
    "What do you call an old snowman? A glass of water.",
    "Who eats snails? People who don’t like fast food!",
    "What did the bathtub say to the toilet? “You look flushed!”",
    "How much does it cost a pirate to get his ears pierced? A buck an ear.",
    "What was a more useful invention than the first telephone? The second telephone.",
    "Why did the banana visit the doctor? She wasn’t peeling well!",
    "What’s a snake’s favorite subject in school? Hiss-tory.",
    "How do you talk to a giant? Use big words.",
    "What did the bald man say when he received a comb for his birthday? “I’ll never part with this!”",
    "Why did the computer get sick? It caught a virus!",
    "Why did the God of Thunder need to stretch his leg muscles so much as a kid? He was a little Thor.",
    "What animal is always at a baseball game? A bat.",
    "How can you tell if an ant is a boy or a girl? They’re all girls! If they were boys, they’d be uncles.",
    "Why did the teacher have a sack full of birdseed? For her parrot-teacher conferences.",
    "What kind of music do mummies listen to? Wrap music.",
    "What falls in winter but never gets hurt? Snow.",
    "How many months have 28 days? All of them!",
    "Why was the broom late to school? It over-swept!",
    "What kind of nut doesn’t like money? Cash ew.",
    "What do you call a ghost’s true love? A ghoul-friend.",
    "What’s white and can’t climb trees? A fridge.",
    "What is the strongest animal in the sea? Mussels.",
    "Why didn’t the lamp sink? It was too light.",
    "What building in New York has the most stories? The public library.",
    "What has three letters and starts with gas? A car.",
    "How does the moon cut his hair? Eclipse it.",
    "What did the elf learn in school? The elf-abet.",
    "What kind of chicken is the funniest? A comedi-hen!",
    "Why do vampires seem sick? They’re always coffin.",
    "How do you get a squirrel to like you? Act like a complete nut!",
    "Why did the farmer ride his horse into town? Because it was too heavy to carry.",
    "What’s a cat’s favorite color? Purrr-ple.",
    "Where do cows go on December 31st? A moo year’s eve party.",
    "What do you call two birds in love? Tweethearts.",
    "Why are ghosts terrible liars? Because you can see right through them.",
    "What does a triceratops sit on? On its tricera-bottom.",
    "What did the snowman ask the other snowman? “Do you smell carrots?”",
    "How does a scientist freshen her breath? With experi-mints.",
    "Why are elevator jokes the funniest? Because they work on so many levels.",
    "What do you call a sleeping T-Rex? A dino-snore!",
    "What did the fisherman say to the magician? “Pick a cod, any cod.”",
    "How are false teeth like stars? They come out at night.",
    "Why was the student’s report card wet? It was below C level.",
    "What kind of pizza do dogs eat? Pup-eroni pizza!",
    "What do Olympic sprinters eat before a race? Nothing, they fast!",
    "What’s worse than finding a worm in your apple? Finding half a worm.",
    "Which side of a cow is the hairiest? The outside!",
    "What do cats wear to bed? Paw-jamas!",
    "Why do bowling pins have such a hard life? They’re always getting knocked down.",
    "What is a computer's favorite snack? Computer chips.",
    "Why did the M&M go to school? Because she wanted to be a Smartie.",
    "What kind of pictures do turtles take? Shell-fies.",
    "Why did the golfer wear two pairs of pants while he played? In case he got a hole in one.",
    "What was the first animal in space? The cow that jumped over the moon.",
    "What do you call a famous turtle? A shell-ebrity!",
    "Why are penguins socially awkward? Because they don’t know how to break the ice.",
    "What did the banana say to the dog? Nothing. Bananas can’t talk.",
    "What type of key opens a banana? A mon-key.",
    "What do you feed an alligator? Anything it wants!",
    "How does a cucumber become a pickle? It goes through a jarring experience.",
    "What time is it when the clock strikes 13? Time to get a new clock.",
    "Why did the melon jump into the river? Because it wanted to be a watermelon.",
    "What makes a sick lemon feel better? Lemon-aid.",
    "Where do you learn to make ice cream? Sundae school.",
    "Why can’t you trust zookeepers? They love cheetahs.",
    "How does Spiderman do research? On the World Wide Web!",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "What do you think of that new diner on the moon? Food was good, but there really wasn’t much atmosphere.",
    "What do Alexander the Great and Kermit the Frog have in common? The same middle name.",
    "What’s the largest gem on earth? A baseball diamond!",
    "What animal dresses up and howls? A wearwolf.",
    "Why did the dinosaur cross the road? Because the chicken wasn’t born yet.",
    "What do you get if you dip a baby cat in chocolate? A Kitty-Kat Bar!",
    "What's red and bad for your teeth? A brick.",
    "Why can’t Elsa have a balloon? Because she’ll let it go.",
    "Why did the farmer jump on his potato plants? Because he wanted mashed potatoes.",
    "What food is never on time? Choco-late!",
    "What did the mama elephant say to her kids when they weren’t behaving? “Tusk, tusk.”",
    "How do you make an octopus laugh? With ten-tickles.",
    "What did the fish say when he bumped into a concrete wall? “Dam!”",
    "What cookie flavor do monkeys love? Chocolate Chimp!",
    "What are bald sea captains most worried about? Cap-sies.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "Why did the puppy do so well at school? Because she was the teacher’s pet!",
    "Why do hurricanes wear a monocle to see? Because they have one eye.",
    "What do you call a retired vegetable? A has-bean."
    ];
    //show joke
    let jokeNumber = Math.floor(Math.random() * Alljokes.length);
    let joke = Alljokes[jokeNumber];
    let showJoke = document.getElementById("main");
    showJoke.innerHTML = joke;
    function nextJoke()
    {
        let jokeNumber = Math.floor(Math.random() * Alljokes.length);
        let joke = Alljokes[jokeNumber];
        let showJoke = document.getElementById("main");
        showJoke.innerHTML = joke;
        console.log(Alljokes.length);
    }
        
//added
const next = document.getElementById('but');
// Add click event listener to the button
next.addEventListener('click', nextJoke);    